### ISSUE TITLE
Automating the double/quadruple res line in encode.avs.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/TASEncodingPackage#17]
Just above [line 135](https://github.com/TASEmulators/TASEncodingPackage/blob/f75677c09d5481d48e1e2e56af1eb8c47eb8531a/encode.avs#L135) this should cover the auto double res being done on every console system, and also for handhelds quad the size.

For the other more modern handhelds which is 3/DS double is used instead, and for future proofing PSP (480x272) as well if that day ever comes.

And as the warning, this isn't something I verified if it works on the encode.avs script as I actually don't use it, but this should work when implemented at the line I suggested.

```
handheld ? last.height > 270 ? PointResize(last.width*2,last.height*2) : \
PointResize(last.width*4,last.height*4) : \
last.height < 400 ? PointResize(last.width*2,last.height*2) : 0
```

The 400 is based on what fsvgm777 has suggested

**Comment by vadosnaprimer** [comment]
@fsvgm777 do we want to have this kind of automation? I wanted to make the baseline script very basic, and then people could add things they need on top, locally, to avoid maintaining infinite checks and hacks.

Naturally it feels there just needs to be an override option in case something isn't covered by the automatic thing, or we just need to go through known resolutions of our consoles and check which factor will be needed for each, automating based on that?

**Comment by fsvgm777** [comment]
I wouldn't be necessarily opposed to having it, but I'd like an option to have it done manually as well (like how it's done in the package) for the less usual cases. (i.e. cases where the width is smaller than height on handheld mode, e.g. several Flash games)

**Comment by Spikestuff** [comment]
So something like this then if we're focusing strictly on Flash games?
And also enabling handheld to also prevent the aspect correction at the next part.

Hindsight I should've named it "prescaleFactor" instead of "override", but that can be fixed in post whenever a decision is made.

```
override = 2
handheld = false

override > 1 ? Eval("""handheld = true \
PointResize(last.width*override,last.height*override)""") : \
handheld ? last.height > 270 ? PointResize(last.width*2,last.height*2) : \
PointResize(last.width*4,last.height*4) : \
last.height < 400 ? PointResize(last.width*2,last.height*2) : 0
```

First two lines in this code snippet would be at [line 20](https://github.com/TASEmulators/TASEncodingPackage/blob/f75677c09d5481d48e1e2e56af1eb8c47eb8531a/encode.avs#L20).

**Comment by vadosnaprimer** [comment]
Do we want to upscale Wii?

**Comment by Spikestuff** [comment]
> Do we want to upscale Wii?

Wii/GCN resolution is at/above 480 which the point was to not double res anything above that resolution (400p), same with PlayStation/N64.
I'm just echoing what I recall in that conversation which was a "soft no" if I'm not mistaken.

**Comment by fsvgm777** [comment]
Yeah, what Spikestuff said.

**Comment by vadosnaprimer** [comment]
I mean Wii video in our encodes is 360p, even if the signal is meant to be 480p technically.

**Comment by Spikestuff** [comment]
...Isn't Wii meant to be 540?
![SMNP01_2022-05-01_19-05-07](https://user-images.githubusercontent.com/12412764/166139345-666ffa67-71df-4508-90a3-aee80af38795.png)

**Comment by fsvgm777** [comment]
I think it's actually meant to be 480 (576 for regular PAL?) across the board. Dolphin's logic is a bit too whack for me.
