### ISSUE TITLE
Implementing support for WonderSwan roatations in an .avsi by letterboxing.

### ISSUE THREAD

**Issue by Spikestuff** [TASVideos/TASEncodingPackage#18]
[New script information comes from this page](https://tasvideos.org/HomePages/Spikestuff/Scripts).
All naming used will be under the unnamed thing I've called it.

On the .avsi file adding this below the default multi-segment should work.
```
# Multisegment AVI import (Letterbox)
function AppendSegmentLetterbox(
\   clip sample,
\ string base,
\    int target_width,
\    int target_height,
\    int first_val,
\    int last_val,
\ string format,
\ string pix_type
\){
    filename = base + string(first_val, format) + ".avi"
    result = AviSource(filename, pixel_type=pix_type)
    xside = int(target_width - result.width) / 2
    yside = int(target_height - result.height) / 2
    result = result.AddBorders(xside,yside,xside,yside)
    return (first_val < last_val) \
        ? result + sample.AppendSegmentLetterbox(base, target_width, target_height, first_val+1, last_val, format, pix_type) \
        : result
}
```

On the .avs side of [support adding at the start](https://github.com/TASEmulators/TASEncodingPackage/blob/x64/encode.avs#L51):
```
CHECKRENAME = true      # enable multisegment import (letterbox)
ms = false           	# enable multisegment import
```

Since my script was made for avs and not avs+ it doesn't support GScript stuff so putting the first bit into the other bit is more important.
I would put this [just before the ms script goes through](https://github.com/TASEmulators/TASEncodingPackage/blob/x64/encode.avs#L180) so it can also disable ms on the complete off chance it was accidentally enabled (and forcing handheld).
```
WSRENAME = Eval("""
	target_width = 224
	target_height = 224""") 

#    Checking for WonderSwan
CHECKRENAME ? Eval("""
    ms = false
    handheld = true
    ((Last.width == 224) && (Last.height == 144)) || \
    ((Last.width == 144) && (Last.height == 224)) ? \
    WSRENAME : false
    """) : false
```

And then lastly [at the ms line](https://github.com/TASEmulators/TASEncodingPackage/blob/x64/encode.avs#L180) changing it after the "resized =" as:
```
CHECKRENAME ? AppendSegmentLetterbox(ms_base, target_width, target_height, ms_start, ms_end, ms_format, pixelType).ConvertToRGB32() : \
ms ? AppendSegment(ms_base, ms_start, ms_end, ms_format, resizer).ConvertToRGB32() : last
```

Possibly adding back at line 51 will help for future systems that split dumps on rotation:
```
target_width = 0
target_height = 0
```
What I provided was mainly to focus on strictly WonderSwan (and then eventually leaving it open for whatever else has to be interjected).

**Comment by vadosnaprimer** [comment]
The queue is very busy right now so this will have to wait.

**Comment by vadosnaprimer** [comment]
What if we make the existing MSImport function optionally apply letterboxing instead of resizing? I'm thinking of making it parse all the files to determine the biggest resolution, and then actually importing them all, letterboxed to that resolution.
